<h3>Details By Message<?php echo (isset($this->adContent)) ? " ({$this->adContent})" : ''; ?></h3>
<hr>

<div>
<h5>Messages Per Day</h5>
<table cellpadding="0" cellspacing="0" border="0" class="display table1" id="table1" width="100%">
    <thead>
        <tr>
            <th>Date</th>
            <th>Day</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>

<?php if (!empty($this->statisticsDaily)): ?>
    <?php foreach($this->statisticsDaily as $stats): ?>
        <tr class="odd">
            <td><?php echo "<a href='#'>".$stats['date']."</a>" ?></td>
            <td><?php echo "<a href='#'>".$stats['day']."</a>" ?></td>
            <td><?php echo $stats['amount'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    </table>
<?php else: ?>
        <tr>
            <td>No Data Found</td>
            <td>No Data Found</td>
            <td>No Data Found</td>
        </tr>
    </tbody>
    <tfoot>
    </table>
<?php endif; ?>
</div>
<div>
<h5>Messages Per Month</h5>
<table cellpadding="0" cellspacing="0" border="0" class="display table1" id="table1" width="100%">
    <thead>
        <tr>
            <th>Month</th>
            <th>Year</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>

<?php if (!empty($this->statisticsMonthly)): ?>
    <?php foreach($this->statisticsMonthly as $mStats): ?>
        <tr class="odd">
            <td><?php echo "<a href='#'>".$mStats['month']."</a>" ?></td>
            <td><?php echo "<a href='#'>".$mStats['year']."</a>" ?></td>
            <td><?php echo $mStats['amount'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    </table>
<?php else: ?>
        <tr>
            <td>No Data Found</td>
            <td>No Data Found</td>
            <td>No Data Found</td>
        </tr>
    </tbody>
    <tfoot>
    </table>
<?php endif; ?>
</div>

<?php if(isset($this->errorMessage)): ?>
    <h2><?php echo $this->errorMessage ?></h2>
<?php endif; ?>