<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<?php echo $this->headTitle(); ?>
<?php 
    $this->headLink()
            ->prependStylesheet($this->baseUrl().'/public/css/global.css')
            //->appendStylesheet('/css/ui-lightness_1.7.3/jquery-ui-1.7.3.custom.css')
            ->appendStylesheet($this->baseUrl().'/public/css/ui-lightness/jquery-ui-1.8.16.custom.css')
            ->appendStylesheet($this->baseUrl().'/public/css/ui.jqgrid.css');
    
    $this->headScript()->appendFile($this->baseUrl().'/public/js/jquery-ui-timepicker-addon.js');
    $this->headScript()->appendFile($this->baseUrl().'/public/js/grid.locale-en.js');
    //$this->headScript()->appendFile($this->baseUrl().'/public/js/jquery.jqGrid.min.js');
?>

<?php echo $this->headLink(); ?>
<?php $this->jQuery()->enable()->uiEnable(); ?>
<?php 
    $this->jQuery()->enable();
    if ($this->jQuery()->isEnabled()) {
        $this->jQuery()->setUiVersion('1.8.16')
                        ->setVersion('1.6.4');
        echo $this->jQuery();
    }
?>
<?php if ($this->dojo()->isEnabled()){
    $this->dojo()->setLocalPath($this->baseUrl().'/public/js/dojo/dojo.js')
                 ->addStyleSheetModule('dijit.themes.claro');
    echo $this->dojo();
   }
?>
<?php echo $this->headScript(); ?>
<meta http-equiv="Expires" content="Fri, Jan 01 1900 00:00:00 GMT">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Lang" content="en">
<meta name="author" content="">
<meta http-equiv="Reply-to" content="@.com">
<meta name="generator" content="PhpED 5.8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="creation-date" content="01/01/2009">
<meta name="revisit-after" content="15 days">
</head>
<body class="claro">
  <div id="xouter">
    <div id="xcontainer">
        <?php echo $this->layout()->content; ?>
    </div>
  </div>
</body>
</html>
